### ISSUE TITLE
Mutant Animals Mod doesn't give appropriate faction flags to its creatures.

### ISSUE THREAD

**Issue by Megadeadly** [Kenan2000/BrightNights-Structured-Kenan-Modpack#131]
I hope this is the right place to put this issue...

I was messing around with a natural spawned Direwolf, as it's description said a whelp could be tamed, and "forced" it to have a baby via map editing its baby timer to 1. Upon doing so, leaving, waiting, and coming back (Via tele), it did indeed make a direwolf whelp, and then, immediately killed it. After spawning in other direwolves, direwolf whelp with the direwolf, as well as packs of some of the other mutated canines from the mod, I saw they ALL immediately went and killed all their siblings and kids, respectively.

I'm no modder, and I'm not that great at reading the files, but it looks like their may be a faction mismatch, as the base that all the creatures inherit sets their base faction as "dog", but then instead has them all set as "Monster", which I assume is in effect making them all regard even duplicates of themselves as being from another faction, instantly causing the infighting. I'm glad I forced the Direwolf to reproduce rather than waiting the time personally, as finding this out organically like I had been planning would have pissed me off to no end, seeing as it takes 270 days for a Direwolf to reproduce, not including finding it or evo. Finally getting a whelp to spawn, and then having it get killed in front of me would easily be a save deletion, as by that point I'd be otherwise done with my save in most cases. If nothing else, it's causing what I would assume is undesired infighting and unintended lowering of enemies from them killing each other.

|
|

Extraneous:
On a side note, and you are free to ignore this section, are there any better ways of spawning in entities that mimics as if it was done naturally? Especially since when I do debug>map>map editor>edit monster, it doesn't let me add any text in the edit function, but lets me delete it only, for some reason, and when spawned via the debug spawn monster also tends to set some flags to null, and completely exclude some fields. that leaves what I'm able to do being some pretty crude selective deletion, and/or total RNG to find a natural spawn to be found to have what I want to happen happen. Didn't have any luck looking up information for how to do this either. Also, any way of setting something as a "pet" rather than just friendly? If you'd got any guides or links to point me in the right direction, if you'd rather not explain everything yourself, I'd be quite happy with that too.

**Comment by Kenan2000** [comment]
Hmm, all monsters definitions have copy-from in them, which means that they should copy all factions parameters correctly, still, I have added factions definitions to all abstract monsters definitions based on what you say, that because of abstract monster definitions not having directly defined factions parameters, monsters that copy from abstract don't have factions also, this fixes it, if not, this is a core game issue with monsters ignoring factions when using copy-from or parameters being ignored when there are multiple copy-from parameters used, which you can post as an issue to fix on Bright Nights repository, I have fixed these errors in this update hopefully 

I am not particularly savvy with regards to advanced in-game debug functions, I honestly know basic game stuff, you can ask developers your questions about game on Bright Nights discord server link to which one can find online

**Comment by Megadeadly** [comment]
I spawned them in, no infighting, looks like what you did worked! Thanks for doing this man, I appreciate it.

**Comment by Kenan2000** [comment]
No problem
