### ISSUE TITLE
hypovolemia effect debug message

### ISSUE THREAD

**Issue by Ignaramico** [Kenan2000/BrightNights-Structured-Kenan-Modpack#171]
the BL9 mod (the 100% resistance one, havent tested the others) throws a negligible error because of the effect of "hypovolemia", while you can ignore it (by pressing selecting that option when the debug message shows) the effect seems to happen too regularly and makes the game have a little lag spike (specially on the maps from the mod since there are a lot of enemies that uses the effect i guess)

![Screenshot from 2024-01-20 20-49-22](https://github.com/Kenan2000/BrightNights-Structured-Kenan-Modpack/assets/34730575/b669ed83-b79e-4b67-89f9-b0ab715e467b)

**Comment by Kenan2000** [comment]
No problem. No, you are not. I really appreciate that you have posted this, this is a very valuable report. Yeah, I have closed your pull request because I have looked into it myself finding that there were more files than one throwing this error before I have fixed this. Hopefully fixed in this update as well
