### ISSUE TITLE
Dropping Compound Greatbow (high) changes it to Compund Bow (high)

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [Kenan2000/BrightNights-Structured-Kenan-Modpack#31]
From the mod Make_Bows_Great_Again , when you shift+a and tighten the limbs on a Compound Great bow it changes to Compound Greatbow (high), when you then drop that Compound Greatbow (high) it'll change to Compund Bow (high), an entirely different bow altogether.

**Comment by CV514** [comment]
I've looked into that and it seems to be working as intended, there just a little issue with name strings (but via id it's actually an correct bow)

Section in question:

```
    "id": "compgreatbow_high",
    "copy-from": "compgreatbow",
    "type": "GUN",
    "name": { "str": "compound bow (high)", "str_pl": "compound bows (high)" },
```

`"str": "compound bow (high)"` should be `"str": "compound greatbow (high)"` because there is indeed a completely different bow with `"id": "compbow_high"` and those bows should not share same name.

Will do a PR, for now you can make that change yourself. Change `compound bow` to `compound greatbow` on lines 314 and 329 in `Archery_override.json`
