### ISSUE TITLE
Drunken Master in Wandering Masters uses Russian text

### ISSUE THREAD

**Issue by Relgar** [Kenan2000/BrightNights-Structured-Kenan-Modpack#74]
He's the only one who has that - this should be changed to English and the normal translation mechanism used instead (Transifex?)

**Comment by CV514** [comment]
Indeed, and it seems like it's been like that since the beginning, which can be viewed in previous forks: https://github.com/CurtV5/Bright-Nights-Kenan-Mod-Pack/blob/666b699662dc7ab246c3c38e827a95ac8e6cf9f1/Kenan-BrightNights-Modpack/Wandering_Masters-bright-nights/npc/Teachers/drunken_master.json

I'll do a PR to change those lines into English and provide proper lang files for Russian translation later.

**Comment by Kenan2000** [comment]
This is hopefully fixed thanks to @CV514's work as well
