### ISSUE TITLE
PK's Rebalancing Mod breaks Overrun scenario

### ISSUE THREAD

**Issue by Spodershibe** [Kenan2000/BrightNights-Structured-Kenan-Modpack#79]
The military warehouse that you spawn in is unable to generate, and after enabling and disabling mods, this is the one causing the issue
https://pastebin.com/KAYMUVhw

**Comment by Kenan2000** [comment]
@Spodershibe Can you trace exactly what causes this via deleting files from mod then checking? Generated debug log does not provide actually comprehensible information, either delete scenarios, professions or start locations one by one to see what part of mod causes this issue so that we can try to find it, fix it hopefully as well

**Comment by Spodershibe** [comment]
> @Spodershibe Can you trace exactly what causes this via deleting files from mod then checking? Generated debug log does not provide actually comprehensible information, either delete scenarios, professions or start locations one by one to see what part of mod causes this issue so that we can try to find it, fix it hopefully as well

After further testing it seems to be somewhat (but not entirely) sporadic and contributed to by several other mods. It is probably contributed to by multiple mods in this pack, but this doesn't help with a solution

**Comment by Kenan2000** [comment]
Then I will close this issue for now until you find more details about it, it's too vague to fix like this as well
